---
-
  name: Update RHEL and Debian
  hosts: all
  become: yes
  tasks:
    -
      name: Updating RHEL
      yum:
        name: "*"
        state: latest
      when: ansible_os_family == "RedHat"
    -
      name: Updating Debian
      apt:
        name: "*"
        state: latest
      when: ansible_os_family == "Debian"
